# Generated by Django 4.2.9 on 2024-02-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kjv', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostScripture',
        ),
    ]
