# Generated by Django 4.2.9 on 2024-02-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kjv', '0002_rename_post_postscripture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postscripture',
            old_name='verse',
            new_name='scripture_reference',
        ),
    ]
